"""The README's tables of results, rebuilt from the generated reports (./lab readme).

The README quotes two summaries: the casebook's (statements, fixes, buffers and median times
before and after) and the drills' durations. Both are copied here from the committed reports
rather than by hand, so the README cannot drift from them. Each block sits between
`<!-- pglab:NAME -->` and `<!-- /pglab:NAME -->` markers; everything outside the markers is
left as it is. The reports are Markdown written by this package, so their tables are parsed
back with a small GitHub-table reader.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from pglab.errors import LabError
from pglab.report import table

BLOCK = re.compile(
    r"(?P<open><!-- pglab:(?P<name>[a-z-]+) -->\n)"
    r"(?P<body>.*?)"
    r"(?P<close><!-- /pglab:(?P=name) -->)",
    re.DOTALL,
)
CELL_SPLIT = re.compile(r"(?<!\\)\|")
SIZE_SUFFIX = re.compile(r"\s+\([^)]*\)$")

# Drill reports in the order the README lists them, with the label of each.
DRILL_REPORTS = (
    ("pitr-drill.md", "PITR, to the time recorded before the accident"),
    ("pitr-drill-name.md", "PITR, to a restore point"),
    ("switchover-drill-pg1-to-pg2.md", "Planned switchover, pg1 to pg2"),
    ("switchover-drill-pg2-to-pg1.md", "Planned switchover, pg2 to pg1"),
    ("failover-drill.md", "Unplanned failover (primary killed)"),
)


@dataclass(frozen=True)
class Report:
    """One generated report: its header facts and its tables, each under its heading."""

    path: str  # as linked from the README, e.g. reports/casebook.md
    header: dict[str, str]  # "Generated by", "Data", "Environment", "Timings", ...
    tables: list[tuple[str, list[list[str]]]]  # (heading above the table, rows incl. header)

    def table_under(self, heading: str) -> list[list[str]]:
        for title, rows in self.tables:
            if title == heading:
                return rows
        raise LabError(f"{self.path}: no table under the heading {heading!r}")


def split_row(line: str) -> list[str]:
    """The cells of a table row, with the pipes that report.table() escaped restored."""
    cells = CELL_SPLIT.split(line.strip())
    return [cell.strip().replace("\\|", "|") for cell in cells[1:-1]]


def parse_report(text: str, path: str) -> Report:
    header: dict[str, str] = {}
    tables: list[tuple[str, list[list[str]]]] = []
    heading = ""
    rows: list[list[str]] = []
    for line in [*text.splitlines(), ""]:
        if line.startswith("|"):
            cells = split_row(line)
            if not all(re.fullmatch(r":?-{3,}:?", cell) for cell in cells):
                rows.append(cells)
            continue
        if rows:
            tables.append((heading, rows))
            rows = []
        if line.startswith("#"):
            heading = line.lstrip("#").strip()
        # The header lines of report.RunInfo: "- Generated by `cmd` on date.", "- Data: ...".
        match = re.match(r"^- (Generated by) (.*)$", line) or re.match(
            r"^- (Data|Server|Environment|Timings): (.*)$", line
        )
        if match and match.group(1) not in header:
            header[match.group(1)] = match.group(2)
    return Report(path, header, tables)


def _generated(report: Report) -> tuple[str, str]:
    """('./lab casebook --measure', '2026-10-02 17:40 UTC') from the 'Generated by' line."""
    match = re.match(r"^`(.+)` on (.+?)\.?$", report.header.get("Generated by", ""))
    if not match:
        raise LabError(f"{report.path}: no 'Generated by' line")
    return match.group(1), match.group(2)


def _scale(report: Report) -> str:
    """'SCALE=10000000 (about 10,000,000 order lines)' from the 'Data' line."""
    data = report.header.get("Data", "")
    return data.split("), ", maxsplit=1)[0] + ")" if "), " in data else data.rstrip(".")


def casebook_block(report: Report) -> str:
    rows = report.tables[0][1] if report.tables else []
    expected = ["#", "Case", "Fix", "Buffers before", "Buffers after"]
    if not rows or rows[0][:5] != expected or len(rows[0]) < 7:
        raise LabError(f"{report.path}: the first table is not the casebook summary")
    command, when = _generated(report)
    out_rows = []
    for row in rows[1:]:
        number, case, fix, before, after, median_before, median_after = row[:7]
        out_rows.append(
            (
                number,
                case.replace("](#", f"]({report.path}#"),
                fix,
                SIZE_SUFFIX.sub("", before),
                SIZE_SUFFIX.sub("", after),
                median_before,
                median_after,
            )
        )
    timings = report.header.get("Timings", "see the report").rstrip(".")
    lines = [
        f"The summary of [{report.path}]({report.path}), written by `{command}` on {when} at "
        f"{_scale(report)}. Buffers are the 8 kB pages a statement read, before and after its "
        f"fix. Times: {timings}.",
        "",
        table(
            [
                "#",
                "Statement (from the TopFlow API)",
                "Fix",
                "Buffers before",
                "Buffers after",
                "Median before",
                "Median after",
            ],
            out_rows,
            "rllrrrr",
        ),
    ]
    return "\n".join(lines)


def drills_block(reports: Sequence[tuple[str, Report]]) -> str:
    rows = []
    commands = []
    for label, report in reports:
        command, _ = _generated(report)
        commands.append(command)
        checks = report.table_under("Checks")[1:]
        passed = sum(1 for row in checks if len(row) > 1 and row[1] == "pass")
        link = f"[{label}]({report.path})"
        for measure, value in report.table_under("Timings")[1:]:
            rows.append((link, measure, value, f"{passed} of {len(checks)}"))
    if not reports:
        raise LabError("no drill reports to summarise")
    first = reports[0][1]
    lines = [
        f"From the drill reports, at {_scale(first)}; every value is from one run of the "
        f"drill ({', '.join(f'`{c}`' for c in dict.fromkeys(commands))}).",
        "",
        table(["Drill", "Measure", "Value", "Checks passed"], rows, "llrr"),
    ]
    return "\n".join(lines)


def environment_block(report: Report) -> str:
    environment = report.header.get("Environment", "not recorded").rstrip(".")
    return f"Environment of these runs, as every report records it: {environment}."


def replace_blocks(readme: str, blocks: dict[str, str]) -> str:
    found: set[str] = set()

    def substitute(match: re.Match[str]) -> str:
        name = match.group("name")
        if name not in blocks:
            return match.group(0)
        found.add(name)
        return f"{match.group('open')}{blocks[name].rstrip()}\n{match.group('close')}"

    text = BLOCK.sub(substitute, readme)
    missing = sorted(set(blocks) - found)
    if missing:
        raise LabError(f"README has no markers for {', '.join(missing)}")
    return text


def build_blocks(reports_dir: Path, link_prefix: str = "reports") -> dict[str, str]:
    def load(name: str) -> Report:
        path = reports_dir / name
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise LabError(f"cannot read {path}: {exc}") from exc
        return parse_report(text, f"{link_prefix}/{name}")

    casebook = load("casebook.md")
    drills = [(label, load(name)) for name, label in DRILL_REPORTS]
    return {
        "casebook": casebook_block(casebook),
        "drills": drills_block(drills),
        "environment": environment_block(casebook),
    }
