"""Markdown helpers and the run metadata printed at the top of every generated report."""

from __future__ import annotations

import os
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime

from pglab.db import Connection, scalar

PENDING = "pending a measured run"


def escape_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def table(headers: Sequence[str], rows: Iterable[Sequence[object]], align: str = "") -> str:
    """A GitHub-flavoured Markdown table. `align` holds one of l/r/c per column."""
    header = "| " + " | ".join(escape_cell(h) for h in headers) + " |"
    marks = []
    for index in range(len(headers)):
        kind = align[index] if index < len(align) else "l"
        marks.append({"l": "---", "r": "---:", "c": ":---:"}.get(kind, "---"))
    lines = [header, "| " + " | ".join(marks) + " |"]
    for row in rows:
        if len(row) != len(headers):
            raise ValueError(f"row has {len(row)} cells, expected {len(headers)}")
        lines.append("| " + " | ".join(escape_cell(cell) for cell in row) + " |")
    return "\n".join(lines)


def code(text: str, language: str = "") -> str:
    fence = "````" if "```" in text else "```"
    return f"{fence}{language}\n{text.rstrip()}\n{fence}"


def ms(value: float | None) -> str:
    """Milliseconds for tables, or the pending marker when the run was not a measured one."""
    if value is None:
        return PENDING
    if value >= 100:
        return f"{value:,.0f} ms"
    if value >= 1:
        return f"{value:.1f} ms"
    return f"{value:.3f} ms"


@dataclass(frozen=True)
class RunInfo:
    """Where and how a report was produced."""

    postgres_version: str
    scale: str
    anchor: str
    environment: str
    generated_at: str
    measured: bool
    runs: int

    def header_lines(self, command: str) -> list[str]:
        timing = (
            f"median of {self.runs} runs after one warm-up run; server-side execution time "
            "from EXPLAIN (ANALYZE, TIMING OFF)"
            if self.measured
            else f"{PENDING}. This was a functional run: plans and buffer counts are real, "
            "durations were not recorded (see docs/benchmarking.md)"
        )
        return [
            f"- Generated by `{command}` on {self.generated_at}.",
            f"- Data: SCALE={self.scale} (about {self.scale_words()} order lines), "
            f"history anchored at {self.anchor}.",
            f"- Server: {self.postgres_version}.",
            f"- Environment: {self.environment}.",
            f"- Timings: {timing}.",
        ]

    def scale_words(self) -> str:
        try:
            return f"{int(self.scale):,}"
        except ValueError:
            return self.scale


def run_info(conn: Connection, *, measured: bool, runs: int) -> RunInfo:
    version = str(scalar(conn, "SELECT version()") or "unknown")
    short_version = version.split(" on ", maxsplit=1)[0]
    scale = scalar(conn, "SELECT value FROM lab.settings WHERE key = 'scale'")
    anchor = scalar(conn, "SELECT value FROM lab.settings WHERE key = 'anchor'")
    return RunInfo(
        postgres_version=short_version,
        scale=str(scale) if scale is not None else "not seeded",
        anchor=str(anchor) if anchor is not None else "n/a",
        environment=os.environ.get("LAB_ENVIRONMENT", "not recorded (run through ./lab)"),
        generated_at=datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC"),
        measured=measured,
        runs=runs,
    )
